# NumPy
NumPy (or Numpy) is a Linear Algebra Library for Python. 
Understanding numpy is important for machine learning/data science and the reason it is so important is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.
# 
Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).
# 
In below sections, I will demonstrate few basic and important numpy functions

# Numpy Arrays
Install Numpy using 'pip install numpy'

In [3]:
# import numpy
import numpy as np 

In [4]:
my_lst = [1,2,3,4]

arr = np.array(my_lst)
print(arr)
print("Shape of the array: ",arr.shape)

[1 2 3 4]
Shape of the array:  (4,)


In [5]:
my_lst1 = [1,2,3,4]
my_lst2 = [5,6,7,8]
my_lst3 = [3,4,5,6]

multi_arr = np.array([my_lst1,my_lst2,my_lst3])
print(multi_arr)
print("Shape of the array: ",multi_arr.shape)

[[1 2 3 4]
 [5 6 7 8]
 [3 4 5 6]]
Shape of the array:  (3, 4)


In [6]:
#  reshaping the array
print("reshape1:",multi_arr.reshape(4,3))
print("reshape2:",multi_arr.reshape(1,12))

reshape1: [[1 2 3]
 [4 5 6]
 [7 8 3]
 [4 5 6]]
reshape2: [[1 2 3 4 5 6 7 8 3 4 5 6]]


# Indexing
It is process accesing elements of list or array using its index value

In [7]:
arr = np.array([1,2,3,4,5,6])

In [8]:
# accesing 3rd element in the array
# remember that in python indexing starts with 0
print("index2",arr[2])
print("index5",arr[5])

index2 3
index5 6


In [9]:
# 2-D indexing
# array[start_row_index:end_row_inedx,start_column_index:end_column_index]
multi_arr[0:3,1:3]

array([[2, 3],
       [6, 7],
       [4, 5]])

# Numpy Inbuilt Functions

In [10]:
# np.aranage returns evenly spaced values within a given interval
# syntax arange([start,] stop[, step,], dtype)
arr = np.arange(0,20,dtype=int)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
# reshaping above array into 2-D array
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
# copy an array to new array and manipulate it
arr1 = arr.copy()
arr1[3:] = 500
print("original array", arr)
print("manipulated array",arr1)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
manipulated array [  0   1   2 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500
 500 500]


In [23]:
# array operations
print("addition",arr1 + arr)
print("subtaction",arr1 - arr)
print("multiplication",arr1 * arr)
print("division",arr1 / arr)
print( "exponential",np.exp(arr))
print("log",np.log(arr))

addition [  0   2   4 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517
 518 519]
subtaction [  0   0   0 497 496 495 494 493 492 491 490 489 488 487 486 485 484 483
 482 481]
multiplication [   0    1    4 1500 2000 2500 3000 3500 4000 4500 5000 5500 6000 6500
 7000 7500 8000 8500 9000 9500]
division [         nan   1.           1.         166.66666667 125.
 100.          83.33333333  71.42857143  62.5         55.55555556
  50.          45.45454545  41.66666667  38.46153846  35.71428571
  33.33333333  31.25        29.41176471  27.77777778  26.31578947]
exponential [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06
 8.88611052e+06 2.41549528e+07 6.56599691e+07 1.78482301e+08]
log [      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722

In [21]:
# Generate array of 1's
ones = np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Random distribution
np.random.rand(3,3)

array([[0.42134465, 0.78933921, 0.60839405],
       [0.52514149, 0.47304437, 0.98718499],
       [0.64304971, 0.87054175, 0.24592149]])

In [29]:
# Norma; distribution
np.random.randn(3,3)

array([[ 0.70233267,  0.21289593,  0.60728472],
       [-0.00629092, -0.23232045,  0.22922695],
       [-1.51524076, -0.58858989, -1.21506291]])